### ISSUE TITLE
mouse driver

### ISSUE THREAD

**Issue by MaxSpb69** [guido57/EBAZ4205_SDR_HDMI_PS2#1]
It would be great if you could add Linux mouse driver code to this very interesting project!

**Comment by guido57** [comment]
Hello Max, I'm happy for your interest in my project. You can find the Linux mouse driver code (zgpio) in this repository:
[EBAZ4205_SDR_spectrum/tree/main/PetaLinux/project-spec/meta-user/recipes-modules/zgpio](https://github.com/guido57/EBAZ4205_SDR_spectrum/tree/main/PetaLinux/project-spec/meta-user/recipes-modules/zgpio)

Note there's also the bitbake to build the zgpio.ko module in a petalinux project.

Let me know if it is ok for you and, if you want, what's is the project you are working on.

Good luck. 

Guido

**Comment by MaxSpb69** [comment]
Thank you very much!

regards,
Max.

**Comment by MaxSpb69** [comment]
Hello, Guido! If possible, I would like to get acquainted with the latest version of the Vivado  and  Qt projects. The repositories do not contain complete information. The provided tcl-script contains many references to missing files and cannot be converted to  a project.
Thanks,
Max,

**Comment by guido57** [comment]
Hello Max,I found the problem, I'll do my best to solve it ASAP. GuidoIl 17 giu 2023 09:32, "Max V. Belyachkov" ***@***.***> ha scritto:
Hello, Guido! If possible, I would like to get acquainted with the latest version of the Vivado  and  Qt projects. The repositories do not contain complete information. The provided tcl-script contains many references to missing files and cannot be converted to  a project.
Thanks,
Max,

**Comment by guido57** [comment]
Hello Max, 
I solved the problem. Now the Vivado project is correctly available on https://github.com/guido57/EBAZ4205_SDR_spectrum/tree/main/Vivado
Carefully read and follow the README.md
Bye
Guido

**Comment by MaxSpb69** [comment]
Big thanks, Guido! No more problem with Vivado project. And what about Qt5 sources?

Max.

**Comment by guido57** [comment]
Hello Max, now QT5 source are published on EBAZ4205_SDR_Spectrum. This repository is no more mantained. Please use the issues of EBAZ4205_SDR_Spectrum for any request.
Bye

**Comment by MaxSpb69** [comment]
Many thanks, Guido!
I have already compiled  entire you project, everything works.

best regards,
Max.
